language: node_js
node_js:
  - stable
cache:
  directories:
    - "node_modules"
install:
  - npm install
script:
  - npm run styleguide:build
after_success:
  - bash deploy.sh
env:
  global:
    - secure: "XOpMvhCG5tIP9PLzdghZL++3L0J9mktwprSpOsNWxyLCS6UkSuVTnfuAKm/XAYM9qBJdpZkPrMyA3FYhOA5rN6zAMal9TOjC6Ajf6mDH2l1ecSCEckBIKRU/UeBh3rOi4MUrjsFE3H5pJe47b9vxM2jZ64/5cJl77BQGfYlflWo/inJmBu3q+euMt3xn7PqCU37qQsfGPKIflq9dGQT/zGd1DpUKEDCUfABKvF+86MQw2BDacIVPEYntU5s0b3sYA2N3hs8Z0fQw7xC1D+I+aV3+IqWYMM2PBeKc6XNGLV1QEvBn3qJebHPgxCFs79aMrrurgH8F60gWO9Z3KpdkvOlIkeUxIodn+VlhWz+LC/D6VodECVkp8rNSiKIbKlv6k1WG7ynk2YiaakIkmZDlafEvyhj7e0KIbn60OAlQb2IelBlELH1Evz2BICBfFeHRPi5309AWpw5NbAN+lhT5+M4BP1zTQIEvPc+peHI96qXCONVuOG5E2k/4LdEbBgslJp3VFQFUdj0y6JitT2UAY4o6Sj6N35eHkOcvrUhSjOFiCcpid++8ik4DF5At3S7iAoQZKAdSvDBns9M+vxf/pPr6f64ZVGqdp5DRHd8HIg3e7yyaYAq0x383CWGezcLkF5yEUjbJvAqTWYHPHRn+ktsRB7k49wfGlA3VZRAaNEA="
