language: node_js
node_js:
  - stable
cache:
  directories:
    - "node_modules"
install:
  - npm install
script:
  - npm run styleguide:build
after_success:
  - bash deploy.sh
env:
  global:
    - secure: "S533l6MZA+jWt6d0OHFsZgbmjjtKM9oIu4/icXX60gBcKngBXbSdUD0cTsnvE72NqH40qW0gksHipEsEcASSAFsnhuSxVNA1pRjOOlUIDfpIoDg/MC6ZrU5iEcgiYgR0Z8zu/menzOfuBDkgLDwPV3IhLvhdJNc4Ww65OCEAedk2pWMtW4QR1kQXiqQBy9/W7LIO013NAYpxYNZS9Mm8VRmWqoGaP+nQotFUo04peA8FqiKK3Du0SHm+D+RLrnMWOBC9CFeLJQa30VzpmtYbY2mdGUMxcJ1P4gTw/cZ+GbEc/ZtdQUO50M7h8q2LrEr/vpzw4rwb/PTx3/YbmUwdMlzNGiSmLIFHLUHGj3PjUn0jaekVBa+q9646r2tFdmY7Q3525Iqi66lFtCJS+9A2KhqflSbnbe2S9vYTWMt+j9Zf3p0uwGWEtFZc7NmBpFRc0pefr5DR7UHLl+bwWAWllprRdfw3ag+pRsWHdSuQXsZ6vyOb9cdFIHyrHhPlOmfmE8LSK0uwTUdkH1cxO38oz9tCWp/pSaG9Ce4b8Ux70aD5HH+tJrIGfT+U7W6gHNVz7uUkc0xFnPvLLex/qFI6XwU/FaxJNilr0INA2xPA1TpXNCkyGqGC2wRdDe44ahHw7bsjO4e19zWBMGrcK3NEmOn3w164nOGhE6kuUM8Xk5I"
